### PR TITLE
Updated slug url to atmosphere-cookbook - fixes issue #13

### PR DESCRIPTION
**Pull request by heidinett**
Updated url to point to renamed project slug "atmosphere-cookbook"
Fixes issue 13

### CODE REVIEW

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
The link doesn't seem to exist.

**Comment by navidcy** [comment]
We should put back the link that works until the new link is operable?

**Comment by heidinett** [comment]
That's also what I found. Thought there was something else that needed to be done.
I will reply to Santos.


Heidi Nettelbeck                                         [cid:89ede1ab-3f24-48b8-8652-49b6f90fe5f1]

Team Leader, Atmospheric Modelling Infrastructure

Australian Earth System Simulator (ACCESS-NRI)

T: +61 02 6125 4959 | E: ***@***.******@***.***> | W: access-nri.org.au<https://www.access-nri.org.au/> |

We at ACCESS-NRI acknowledge the Traditional Owners of the land on which our research infrastructure and community operate across Australia and pay our respects

to Elders past and present. We recognise the thousands of years of accumulated knowledge and deep connection they have with all the Earth systems we simulate.


________________________________

**Comment by navidcy** [comment]
Try now? I might have triggered a new build at https://atmosphere-cookbook.readthedocs.io/en/latest/

**Comment by navidcy** [comment]
Works for me

**Pull request merged**
