### PR TITLE
Add Citation section in README.md + docs

### LINKED ISSUE #19: Acknowledgments + Citation
We should include a proposed way for users to acknowledge the repository in papers and potentially also a way to cite it.

### PR DESCRIPTION
**Pull request by navidcy**
This PR adds a "Citation" section in the README and the Docs that urges people to cite the Zenodo record of the repository.

Closes #19

### CODE REVIEW

**Comment by andrewbrown31** [comment]
The citation section is good, and it's nice to have the Zenodo record!

Before merging, is this a good time to add people as contributors that haven't actually pushed code? E.g. @greensh16 worked on [AUS2200_xarray_rolling.ipynb](https://github.com/ACCESS-Community-Hub/atmosphere-cookbook/blob/main/Recipes/AUS2200_xarray_rolling.ipynb) but is not a contributor on the repo

**Review by andrewbrown31 — COMMENTED** [review]
The citation section is good, and its good to have the Zenodo record!

Before merging, is this a good time to add people as contributors who have not actually pushed code? E.g. @greensh16 worked on [AUS2200_xarray_rolling](https://github.com/ACCESS-Community-Hub/atmosphere-cookbook/blob/main/Recipes/AUS2200_xarray_rolling.ipynb) but is not a contributor on GitHub.

**Comment by navidcy** [comment]
> The citation section is good, and its good to have the Zenodo record!
> 
> Before merging, is this a good time to add people as contributors who have not actually pushed code? E.g. @greensh16 worked on [AUS2200_xarray_rolling](https://github.com/ACCESS-Community-Hub/atmosphere-cookbook/blob/main/Recipes/AUS2200_xarray_rolling.ipynb) but is not a contributor on GitHub.

Yes!!! @greensh16 you have an orcid ID?

**Comment by greensh16** [comment]
Thanks @andrewbrown31. Yes my orchid ID is https://orcid.org/0000-0003-1129-4676

**Comment by navidcy** [comment]
I added you @greensh16. Your name will appear the next time we make release (eg after we merge this PR or as soon we add a new recipe).

**Review by andrewbrown31 — APPROVED** [review]

**Comment by heidinett** [comment]
Thanks @navidcy. I added my OrchidID.

**Pull request merged**
