### PR TITLE
Fix repo url in docs

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by navidcy** [comment]
The fact that we don't see the readthedocs preview in the actions in this PR makes me wonder a bit regarding whether everything is set up correctly.

**Review by heidinett — APPROVED** [review]
Thanks for the fix. Link now works!

**Comment by heidinett** [comment]
Correct url for the docs. Fixes PR #15

**Comment by heidinett** [comment]
> The fact that we don't see the readthedocs preview in the actions in this PR makes me wonder a bit regarding whether everything is set up correctly.

I did a rebuild of the Readthedocs for our project. I think that might have fixed it.

**Pull request merged**
